import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Middlemist Events",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={cn("bg-white text-slate-900 antialiased", inter.className)}
    >
      <body
        suppressHydrationWarning={true}
        className="min-h-screen bg-slate-50 antialiased"
      >
        {children}
      </body>
    </html>
  );
}
