type MenuItem = {
  name: string;
  dropdownItems?: (string | { name: string; dropdownItems: string[] })[];
};

export const Featured = [
  {
    title: "Party Supplies",
    content:
      "From tableware to decorations, our comprehensive range of party supplies ensures you have everything you need to create unforgettable gatherings.",
    background: "party-supplies.jpg",
  },
  {
    title: "Cake Topper",
    content:
      "Discover the freshest additions to our collection, designed to infuse your parties with the latest trends and must-have essentials",
    background: "cake-topper.jpg",
  },
  {
    title: "DIY Balloons",
    content:
      "Unleash your creativity with our DIY balloon kits, perfect for adding a personalized touch to your events. Elevate your balloon game with ease!",
    background: "DIY-Balloons.png",
  },
  {
    title: "Party Styling",
    content:
      "Elevate your celebrations with professional balloon styling services. Our experts will transform your venue into a stunning masterpiece of color and elegance, setting the stage for unforgettable moments.",
    background: "party-styling.jpg",
  },
];

export const MenuItems: MenuItem[] = [
  { name: "NEW" },
  {
    name: "BALLOONS",
    dropdownItems: ["DIY Balloons", "Foil Balloons", "Balloon Styling"],
  },
  {
    name: "PARTY SUPPLIES",
    dropdownItems: ["Plates", "Cups", "Napkins", "Straws", "Cake Topper"],
  },
  { name: "PARTY BOXES" },
  {
    name: "SHOP BY THEME",
    dropdownItems: [
      {
        name: "Occassions",
        dropdownItems: ["Bridal Shower", "Baby Shower", "Gender Reveal"],
      },
      {
        name: "Kids Parties",
        dropdownItems: [
          "Unicorn",
          "Mermaid",
          "Princess",
          "Space",
          "Jungle",
          "Bee",
          "Dino",
          "Butterfly",
          "Circus",
          "Cars",
          "Building Blocks",
          "Ice cream",
        ],
      },
    ],
  },
  { name: "SALE" },
];

export const Events = [
  { name: "GENDER REVEAL" },
  { name: "BRIDAL SHOWER" },
  { name: "BABY SHOWER" },
];

export const BalloonStyling = [
  {
    name: "6 Months B'Day",
    description:
      "Celebrate the precious half-year milestone with a delightful 6-month birthday party filled with joy, cute decorations, and sweet memories.",
  },
  {
    name: "Birthday",
    description:
      "A classic and timeless birthday celebration that embraces the joy of growing another year older. Perfect for all ages and customizable to fit any personality or interest.",
  },
  {
    name: "Boss Baby",
    description:
      "Bring the world of Boss Baby to life with a stylish and sophisticated theme inspired by the adorable boss in a suit. Perfect for little ones who love a touch of humor and charm.",
  },
  {
    name: "Frozen",
    description:
      "Dive into the enchanting world of Frozen, where snowflakes glisten, and ice castles gleam. A magical theme inspired by the beloved characters Elsa, Anna, and Olaf.",
  },
  {
    name: "Too Fast",
    description:
      "Rev up the excitement with a Cars-themed party inspired by the animated film. Perfect for little speedsters who love the world of racing and adventure.",
  },
  {
    name: "Little Mermaid",
    description:
      "Transport guests under the sea with a Little Mermaid-themed party. Dive into a world of underwater wonders, mermaids, and ocean treasures for an unforgettable experience.",
  },
  {
    name: "Mermaid",
    description:
      "Create a magical and mystical atmosphere with a Mermaid-themed party. Delight in sea-inspired decor, iridescent colors, and a touch of fantasy for a whimsical celebration.",
  },
  {
    name: "Let's Party",
    description:
      "A versatile and exciting theme that's all about celebrating life and having a good time. Let your creativity shine with colorful decorations and a lively atmosphere.",
  },
];

export const Items = [
  {
    Name: "MERMAID CAKE TOPPER",
    Price: "6",
    Type: "Cake Topper",
    Description:
      "Throw a Beautiful Mermaid theme Birthday party with this elegant mermaid cake topper. Featuring Ocean shells, star fish and little mermaid cake topper will add finishing touch to your beautifully decorated cake. Pack contains 1 Rose gold mermaid cake topper",
    Theme: "Mermaid",
    Material: "Acrylic",
    Colour: "Rose gold",
    Text: "Happy Birthday",
    Dimension: "15 cm x 16 cm",
    Images: [
      "ocean-shell-arylic-happy-birthday-cake-t_main-1.jpg",
      "Y02_1-pc-acrylic-happy-birthday-cake-insert-c_variants-1.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "1",
  },
  {
    Name: "BIRTHDAY 'QUEEN' CAKE TOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your Birthday cake at your special day. Add this birthday ‘Queen’ cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Gold Birthday cake topper.",
    Theme: "Queen",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Birthday Queen",
    Dimension: "12 cm",
    Images: ["crown-birthday-king-queen-princess-princ_main-4.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "2",
  },
  {
    Name: "FLAMINGO CAKE TOPPER",
    Price: "6",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your Birthday cake at your special day. Add this colourful birthday flamingo cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Flamingo Gold Birthday cake topper.",
    Theme: "Flamingo",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: "7.5 cm x 4.5 cm",
    Images: [
      "1.jpg",
      "1pcs cake topper B_flamingo-pineapple-aloha-letter-cake-top_variants-3 - Copy.jpg",
      "1pcs cake topper B_flamingo-pineapple-aloha-letter-cake-top_variants-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "3",
  },
  {
    Name: "HAPPY ANNIVERSARY CAKE TOPPER",
    Price: "6",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Gold Anniversary cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Happy Anniversary cake topper.",
    Theme: "Anniversary",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Anniversary",
    Dimension: undefined,
    Images: ["gold_wedding-cake-topper-acrylic-bride-to-be_variants-17.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "4",
  },
  {
    Name: "UNICORN CAKE TOPPER",
    Price: "14",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Featuring cute little girl sitting on the magical unicorn will add extra magic to your unicorn birthday. Add this Elegant Unicorn cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Unicorn cake topper",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "rainbow-unicorn-girl-baby-shower-1st-cak_main-0.jpg",
      "Unicorn girl_unicorn-girl-straw-cake-topper-for-birth_variants-1.jpg",
      "unicorn-girl-straw-cake-topper-for-birth_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "5",
  },
  {
    Name: "RAINBOW CAKE TOPPER",
    Price: "5",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Magical Rainbow cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Rainbow cake topper",
    Theme: "Rainbow",
    Material: "Paperboard",
    Colour: undefined,
    Text: undefined,
    Dimension: "14 cm x 10.5 cm",
    Images: [
      "A3_rainbow-unicorn-girl-baby-shower-1st-cak_variants-2.jpg",
      "Rainbow clouds 1_unicorn-girl-straw-cake-topper-for-birth_variants-5.jpg",
      "unicorn-girl-straw-cake-topper-for-birth_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "6",
  },
  {
    Name: "SAFARI HAPPY BIRTHDAYCAKE TOPPER",
    Price: "6",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Cute Animal cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Safari Happy Birthday cake topper",
    Theme: "Jungle",
    Material: "Paperboard",
    Colour: undefined,
    Text: undefined,
    Dimension: "15 cm x 15 cm",
    Images: [
      "black_woodland-animals-cake-decor-soft-clay-li_variants-22 - Copy.jpg",
      "black_woodland-animals-cake-decor-soft-clay-li_variants-22.jpg",
      "jungle-animals-cactus-cake-toppers-happy_main-0 (1).jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "7",
  },
  {
    Name: "ONE HAPPY BIRTHDAY CAKE TOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this ‘ONE’ cake topper as the finishing touch to your beautifully decorated cake for your little one’s first Birthday party. Pack contains 1 ‘ONE’ Happy Birthday cake topper",
    Theme: "One",
    Material: "Acrylic",
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "garniture-de-gateau-danniversaire-en-ac_main-3.jpg",
      "one-first-birthday-cake-topper-baby-show_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "8",
  },
  {
    Name: "0-9 NUMBER CAKE TOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. These Number cake toppers are ideal for birthday cake or cup cakes.",
    Theme: "0-9 Number",
    Material: "Acrylic",
    Colour: "Gold",
    Text: undefined,
    Dimension: "10.8 cm x 4 cm (approx)",
    Images: [
      "5-10-pcs-mirror-surface-cake-topper-acryl_description-10.jpg",
      "5-10-pcs-mirror-surface-cake-topper-acryl_description-16.jpg",
      "set-of-11-pcs-acrylic-numbers-0-9-crown-c_main-0.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "9",
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Gold Happy Birthday cake topper.",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: ["acrylic-happy-birthday-cake-topper-for-c_main-0.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "10",
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Gold Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: ["2020-new-laser-cut-cake-party-decoration_main-0.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "11",
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Silver Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Silver",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: [
      "decoration-de-gateau-dore-et-rose-en-res_main-3.jpg",
      "Silver_ins-birthday-cake-topper-paper-butterfly_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "12",
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Rose Gold Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Rose Gold",
    Text: "Happy Birthday",
    Dimension: "13 cm x 13.5 cm",
    Images: [
      "2020-happy-birthday-cake-topper-acrylic_main-3.jpg",
      "happy-birthday-cake-topper-silver-glitte_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "13",
  },
  {
    Name: "HE OR SHE CAKETOPPER",
    Price: "4",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 He or She cake topper",
    Theme: "He or She",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "He or She",
    Dimension: "10.5 cm x 15.5 cm",
    Images: [
      "baby-gender-reveal-for-he-or-she-cake-to_main-1.jpg",
      "gender-reveal-acrylic-cake-topper-decora_main-2.jpg",
      "she-or-he-birthday-cake-toppers-boy-or-g_main-4.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "14",
  },
  {
    Name: "MERMAID CUP",
    Price: "5",
    Type: "Cup",
    Description:
      "This beautiful iridescent mermaid cups are perfect addition to your mermaid theme birthday party. Each pack contains 8 pieces mermaid paper cup",
    Theme: "Mermaid",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "7.5 cm x 8.7 cm",
    Images: [
      "8pcs cups_mermaid-party-colorful-shell-disposable_variants-8.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "15",
  },
  {
    Name: "PRINCESS PAPER CUPS",
    Price: "8",
    Type: "Cup",
    Description:
      "This beautiful pink paper cup is featuring a magical castle with gold foil pressed elements are perfect addition to your princess birthday party. Each pack contains 8 pieces mermaid paper cup",
    Theme: "Princess",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["princess (2).jpg", "Princess.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "16",
  },
  {
    Name: "UNICORN PAPER CUPS",
    Price: "6",
    Type: "Cup",
    Description:
      "This pretty pastel peach unicorn paper cup is beautiful addition to your unicorn theme party. Featuring a fun magical unicorn in the rainbow will add more colours to your birthday party. Each pack contains 8 pieces paper cup",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["0.jpg", "1.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "17",
  },
  {
    Name: "FLAMINGO PAPER CUPS",
    Price: "8",
    Type: "Cup",
    Description:
      "ALOHA!!! This Pretty pink flamingo paper cups are perfect addition to your flamingo or Tropical theme party. Featuring gorgeous colours, pair of flamingo, tropical fruit and gold foil details is the perfect way to serve refreshments at your party. Pair them with our flamingo paper plates or pineapple paper plates for fun flamingo or tropical party. Each pack contains 8 pieces paper cup",
    Theme: "Flamingo",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["flamingo-cup.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "18",
  },
  {
    Name: "BRIDAL SHOWER PAPER CUP",
    Price: "8",
    Type: "Cup",
    Description:
      "Ready to tie the knot! These Elegant Bridal Shower Paper cups are featuring Greenery Eucalyptus with gold foil rim are perfect addition to your Bridal shower party!. Each pack contains 16 pieces paper cup",
    Theme: "Bridal Shower",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "16pcs Paper Cups_16-pcs-bridal-shower-disposable-tableware_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "19",
  },
  {
    Name: "BEE PAPER CUP",
    Price: "8",
    Type: "Cup",
    Description:
      "This beautiful yellow colour paper cups featuring cute bees with yummy honeycomb will add cute addition to your bee theme party. Mix and match with our beautiful paper plates, straws and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Bee",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["bee (2).jpg", "bee.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "20",
  },
  {
    Name: "SWEET UNICORN PAPER CUPS",
    Price: "8",
    Type: "Cup",
    Description:
      "This sweet unicorn paper cups are perfect for serve refreshments in your magical unicorn birthday party. This paper cups are sweetest addition to your party and make memorable one. Mix and match with our beautiful paper plates, straws and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "44-pcs-set-pink-cartoon-unicorn-theme-dis_description-5.jpg",
      "unicorn green.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "21",
  },

  {
    Name: "DINO PAPER CUPS",
    Price: "6",
    Type: "Cup",
    Description:
      "This cute little Dino paper cups are coolest addition to your dinosaur theme party. Mix and match with our beautiful paper plates, straws, napkins and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Dino",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["Dino.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "22",
  },
  {
    Name: "GOLD PAPER CUPS",
    Price: "7",
    Type: "Cup",
    Description:
      "Celebrate your special moments with these beautiful gold paper cups. You can match with these cups with our “oh baby “paper plates to throw an amazing baby shower party. Mix and match with our beautiful paper plates, straws, napkins and other decorations. Each pack contains 10 pieces paper cup",
    Theme: "Baby Shower",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["IMG_E3019.JPG"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "23",
  },
  {
    Name: "WILD ONE PAPER CUPS",
    Price: "9",
    Type: "Cup",
    Description:
      "BE WILD! This pretty paper cups are featuring floral ring with cute baby animals pressed on the paper cups. These paper cups are ideal for baby’s first birthday. Each pack contains 10 paper cups",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["new-wild-party-wild-one-golden-wild-part_main-5.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "24",
  },
  {
    Name: "BUTTERFLY PAPER CUPS",
    Price: "8",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this beautiful butterfly paper cup. Featuring floral soft pink, and butterflies in the paper cups are surely impressed your guest. This paper cups are perfect for butterfly, garden or fairy theme party. Each pack contains 8 paper cups",
    Theme: "Butterfly",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "8Pcs cups_butterfly-theme-party-disposable-tablewa_variants-2.jpg",
      "8PCS_pink-butterfly-pattern-plate-cup-straw-s_variants-1.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "25",
  },
  {
    Name: "CIRCUS PAPER CUPS",
    Price: "9",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cup will bring joy and fun act for your little one who loved to go to carnival or circus. This paper cups are ideal for Circus or Carnival theme party. Each pack contains 8 paper cups",
    Theme: "Circus",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["circus-theme-party-decorations-striped-a_main-5.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "26",
  },
  {
    Name: "WHEELS PAPER CUPS",
    Price: "14",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cup will bring joy and fun for your little one who loves the vehicle. This paper cups are ideal for Wheels or Construction theme party. Each pack contains 10 paper cups",
    Theme: "Cars",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["wheels.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "27",
  },
  {
    Name: "BLOCKS PAPER CUPS",
    Price: "9",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cup will bring joy and fun for your little one who loves to play with Blocks or Duplo. This paper cups are ideal for Blocks or Duplo theme party. Each pack contains 8 paper cups",
    Theme: "Building Blocks",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["2.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "28",
  },
  {
    Name: "PINK PAPER CUPS",
    Price: "9",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cups are perfect for Ice cream theme party. Each pack contains 8 paper cups",
    Theme: "Ice cream",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["ice pop.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "29",
  },
  {
    Name: "SILVER HAPPY ANNIVERSARY ROUND FOIL",
    Price: "4",
    Type: "Foil Balloon",
    Description:
      "Add some beauty to your special day with this Silver Happy Anniversary round foil balloon. Featuring white & yellow flowers and the text ‘Happy Anniversary’ printed on a silver round foil balloon are great choice for your special day.",
    Theme: "Anniversary",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 inch (45 cm)",
    Images: ["Silver_7-pcs-happy-anniversary-foil-balloons-18_variants-0.jpg"],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "30",
  },
  {
    Name: "GOLD HAPPY ANNIVERSARY ROUND FOIL",
    Price: "4",
    Type: "Foil Balloon",
    Description:
      "Add some Glamour to your special day with this Gold Happy Anniversary round foil balloon. Featuring gold design and the text ‘Happy Anniversary’ printed on a white round foil balloon are great choice for your special day.",
    Theme: "Anniversary",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 inch (45 cm)",
    Images: ["gold_10-pcs-happy-anniversary-helium-balloons_variants-3.jpg"],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "31",
  },
  {
    Name: "BLUE HAPPY BIRTHDAY FOIL BALLOON",
    Price: "4",
    Type: "Foil Balloon",
    Description:
      "These Pretty blue color foil balloon is perfect way to celebrate your birthday. These foil balloon will add instant beauty to your special day.",
    Theme: "Happy Birthday",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 inch (45 cm)",
    Images: ["hbd blue.jpg"],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "32",
  },
  {
    Name: "PINK HAPPY BIRTHDAY FOIL BALLOON",
    Price: "4",
    Type: "Foil Balloon",
    Description:
      "These Pretty Pink color foil balloon is perfect way to celebrate your birthday. These foil balloon will add instant beauty to your special day.",
    Theme: "Happy Birthday",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 inch (45 cm)",
    Images: ["5_10-pcs-lot-18-inch-birthday-round-foil-bal_variants-4.jpg"],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "33",
  },
  {
    Name: "IT’S A BOY FOIL BALLOON",
    Price: "4",
    Type: "Foil Balloon",
    Description:
      "Celebrate the biggest upcoming arrival with this beautiful foil balloon. Featuring sky blue mix with green, cute baby clothes and the text ‘it’s a baby boy’ printed on the round foil balloon. This foil balloon is a great choice for baby shower or gender reveal party.",
    Theme: "Gender Reveal",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 inch (45 cm)",
    Images: ["7_10-pcs-lot-18-inch-birthday-round-foil-bal_variants-6.jpg"],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "34",
  },
  {
    Name: "IT’S A GIRL FOIL BALLOON",
    Price: "4",
    Type: "Foil Balloon",
    Description:
      "Celebrate the biggest upcoming arrival with this beautiful foil balloon. Featuring cute baby clothes and the text ‘it’s a baby girl’ printed on the pink round foil balloon. This foil balloon is a great choice for baby shower or gender reveal party.",
    Theme: "Gender Reveal",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 inch (45 cm)",
    Images: ["8_10-pcs-lot-18-inch-birthday-round-foil-bal_variants-7.jpg"],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "35",
  },
  {
    Name: "LARGE ANIMAL FOIL BALLOON",
    Price: "12",
    Type: "Foil Balloon",
    Description:
      "This Super cute Large Animal foil balloons are sure to delight at your jungle theme, safari theme, zoo theme, or any animal party theme birthday party. This foil balloons are sure way to impress your guest as well as your little ones. Quantity: 6pcs,  Shapes of Animals: Cow, Zebra, Lion, Monkey, Giraffe & Tiger",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "As picture show",
    Images: [
      "Large Size 6pc Mixed_6-pcs-safari-party-theme-animal-ballons-j_variants-0.jpg",
      "Large Size Cow_6-pcs-safari-party-theme-animal-ballons-j_variants-2.jpg",
      "Large Size Giraffe_6-pcs-safari-party-theme-animal-ballons-j_variants-6.jpg",
      "Large Size Lion_6-pcs-safari-party-theme-animal-ballons-j_variants-8.jpg",
      "Large Size Monkey_6-pcs-safari-party-theme-animal-ballons-j_variants-10.jpg",
      "Large Size Tiger_6-pcs-safari-party-theme-animal-ballons-j_variants-12.jpg",
      "Large Size Zebra_6-pcs-safari-party-theme-animal-ballons-j_variants-4.jpg",
    ],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "36",
  },
  {
    Name: "SMALL ANIMAL FOIL BALLOON",
    Price: "8",
    Type: "Foil Balloon",
    Description:
      "This Super cute Animal foil balloons are sure to delight at your jungle theme, safari theme, zoo theme, or any animal party theme birthday party. This foil balloons are sure way to impress your guest as well as your little ones. Quantity: 6pcs, Shapes of Animals: Cow, Zebra, Lion, Monkey, Giraffe & Tiger",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "As picture show",
    Images: [
      "Small Cow_6-pcs-safari-party-theme-animal-ballons-j_variants-3.jpg",
      "Small Giraffe_6-pcs-safari-party-theme-animal-ballons-j_variants-7.jpg",
      "Small Lion_6-pcs-safari-party-theme-animal-ballons-j_variants-9.jpg",
      "Small Monkey_6-pcs-safari-party-theme-animal-ballons-j_variants-11.jpg",
      "Small Size 6pc Mixed_6-pcs-safari-party-theme-animal-ballons-j_variants-1.jpg",
      "Small Tiger_6-pcs-safari-party-theme-animal-ballons-j_variants-13.jpg",
      "Small Zebra_6-pcs-safari-party-theme-animal-ballons-j_variants-5.jpg",
    ],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "37",
  },
  {
    Name: "HAPPY BIRTHDAY FOIL BALLOON",
    Price: "4",
    Type: "Foil Balloon",
    Description:
      "This Pretty colorful foil balloon is perfect way to celebrate your birthday. Featuring colorful candles and the text ‘Happy Birthday’ printed on the white foil balloon will add instant beauty to your special day.",
    Theme: "Happy Birthday",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 inch (45 cm)",
    Images: ["S_10-pcs-18-inch-happy-birthday-balloons-rou_variants-19.jpg"],
    BalloonOrPartyItem: "Balloon",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: ["Round foil Balloon"],
    ID: "38",
  },
  {
    Name: "OUTER SPACE NAPKINS",
    Price: "7",
    Type: "Napkin",
    Description:
      "Take a tour to the Outer Space with this awesome rocket shape napkins. This rocket shape napkins are perfect for space party. Pack contains 10 paper napkins",
    Theme: "Space",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "16.5cm X 16.5 cm",
    Images: ["rocket 1.jpg", "rocket 2 (1).jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "39",
  },
  {
    Name: "SWEET PRINCESS NAPKINS",
    Price: "4",
    Type: "Napkin",
    Description:
      "Celebrate your little princess birthday with this pastel pink gold foil pressed elements napkins. This napkins are simply beautiful and will add extra elegance to your princess birthday party. Pack contains 16 paper napkins",
    Theme: "Princess",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "25 cm X 25 cm",
    Images: ["Princess-napkins-the-party-room.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "40",
  },
  {
    Name: "OH BABY NAPKINS",
    Price: "7",
    Type: "Napkin",
    Description:
      "Celebrate your special day with Botanical paper napkins featuring “oh baby” gold text on it. This is perfect for treat everyone in your special day. Pack contains 20 paper napkins",
    Theme: "Princess",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "2.jpg",
      "Fluorescence Yellow_omilut-forest-oh-baby-plates-wild-one-bi_variants-1.jpg",
      "oh baby.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "41",
  },
  {
    Name: "SWEET UNICORN NAPKINS",
    Price: "5",
    Type: "Napkin",
    Description:
      "Host a magical unicorn birthday party with these beautiful napkins. These beautiful pastel pink napkins are cutest addition to your magical birthday. Pack contains 20 paper napkins",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "12.5 cm X 12.5 cm",
    Images: ["unicorn-1.jpg", "unicorn-2.jpg", "unicorn-3.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "42",
  },
  {
    Name: "LITTLE DINO NAPKINS",
    Price: "5",
    Type: "Napkin",
    Description:
      "Create a dinosaur kingdom party with these little dino napkins. Featuring all kind of colourful dinosaurs is perfect addition to your dinosaur party. Pack contains 10 paper napkins",
    Theme: "Dino",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm",
    Images: [
      "dino.jpg",
      "parties-tour-dino-party-dinosaur-paper-st_main-5.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "43",
  },
  {
    Name: "WILD ONE NAPKINS",
    Price: "9",
    Type: "Napkin",
    Description:
      "BE WILD! Featuring beautiful floral ring with cute little animals will add instant beauty to your jungle or animal theme party. Pack contains 10 paper napkins",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "17 cm X 17 cm",
    Images: [
      "wild one 1.jpg",
      "wild-one-1st-birthday-forest-animal-tabl_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "44",
  },
  {
    Name: "BEE NAPKINS",
    Price: "5",
    Type: "Napkin",
    Description:
      "BUZZZZ... These awesome yellow bee napkins are sure to delight at your bee theme birthday party. Featuring honeycomb, bees and flowers are add some colours to your event. Pack contains 10 paper napkins",
    Theme: "Bee",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm ",
    Images: ["bee.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "45",
  },
  {
    Name: "WHEELS NAPKINS",
    Price: "15",
    Type: "Napkin",
    Description:
      "These awesome paper napkins are sure to delight at your Wheels theme birthday party. Featuring the Fire truck, school bus, police car, & construction vehicles pressed in blue stripe napkins are perfect for Wheels, Vehicle or Construction theme party. Pack contains 20 paper napkins",
    Theme: "Cars",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm ",
    Images: ["wheels.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "46",
  },
  {
    Name: "CIRCUS NAPKINS",
    Price: "9",
    Type: "Napkin",
    Description:
      "These awesome paper napkins are sure to delight at your circus theme birthday party. Featuring all the circus animals and performers will add some fun to your party settings. Pack contains 10 paper napkins",
    Theme: "Circus",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm ",
    Images: ["wheels.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "47",
  },
  {
    Name: "BUTTERFLY NAPKINS",
    Price: "10",
    Type: "Napkin",
    Description:
      "These awesome paper napkins are sure to delight at your Butterfly theme birthday party. Featuring the flowers and butterfly pressed in soft pink napkins are perfect for Butterfly, Garden or Fairy theme party. Pack contains 20 paper napkins",
    Theme: "Butterfly",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm ",
    Images: ["butterfly-theme-party-disposable-tablewa_main-4.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "48",
  },
  {
    Name: "BLOCKS NAPKINS",
    Price: "14",
    Type: "Napkin",
    Description:
      "These awesome paper napkins are sure to delight at your little ones Blocks theme birthday party. Featuring an iconic Block colours orange, red, yellow, green, royal blue and Happy Birthday Letters write down in the napkins are perfect for Blocks or Duplo theme party. Pack contains 10 paper napkins",
    Theme: "Building Blocks",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm ",
    Images: ["blocks.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "49",
  },
  {
    Name: "ICE CREAM NAPKINS",
    Price: "11",
    Type: "Napkin",
    Description:
      "These awesome paper napkins are sure to delight at your little ones Ice cream theme birthday party.  Pack contains 20 paper napkins",
    Theme: "Ice cream",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm ",
    Images: [
      "Napkins 20pcs_summer-ice-cream-disposable-party-tablew_variants-4.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "50",
  },
  {
    Name: "UNICORN THEME PAPER PLATES",
    Price: "8",
    Type: "Plates",
    Description:
      "These Super cute Unicorn paper plates will add Fun and Magic to your party! Featuring pretty pastel peach plate with gold touch unicorn standing on the magical rainbow paper plates will add shine to your Unicorn Party! Pack of 8 plates",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18cm ( 7inch)",
    Images: ["unicorn-1.jpg", "unicorn-2.jpg", "unicorn-3.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "51",
  },
  {
    Name: "PRINCESS PAPER PLATES",
    Price: "8",
    Type: "Plates",
    Description:
      "These Elegant paper plates featuring blush pink with gold foil elements are beautiful addition to your Princess theme Birthday party!  Each pack contains 8 paper plates",
    Theme: "Princess",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18.5 cm (7.5 inch)",
    Images: [
      "Princess-plates-the-party-room.jpg",
      "princess-theme-party-decorations-disposa_main-0.jpg",
      "princess-theme-party-decorations-disposa_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "52",
  },
  {
    Name: "OUTER SPACE PAPER PLATES",
    Price: "14",
    Type: "Plates",
    Description:
      "3...2.1 Blast-off Take a tour to the Outer Space with these exquisite paper plates. Featuring a space scene filled with stars, planets and rocket ships are perfect for Space or Astronaut themed birthday party. Each pack contains 8 paper plates",
    Theme: "Space",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "22.5 cm (9 inch)",
    Images: [
      "03.jpg",
      "outer-space-theme-party-disposable-table_main-1.jpg",
      "space.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "53",
  },
  {
    Name: "SWEET UNICORN PAPER PLATES",
    Price: "8",
    Type: "Plates",
    Description:
      "This pretty unicorn paper plates are perfect for celebrate magical birthday party. Featuring mint green and detail with rainbow, cupcake, ice cream, and adorable white unicorn add some colours to your event. Each pack contains 8 paper plates",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18.5 cm",
    Images: ["1.jpg", "mint green.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "54",
  },
  {
    Name: "IN TO THE JUNGLE PAPER PLATES",
    Price: "12",
    Type: "Plates",
    Description:
      "Calling all the Animals! This Beautiful paper plates are greatest addition to your wild, Jungle or Safari theme Birthday party. In the jungle you will found the zebra, snake, tiger, cheetah, and lion and get wild with these awesome plates. Each pack contains 8 paper plates",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "23 cm (9 inch)",
    Images: [
      "0 (1).jpg",
      "0 (2).jpg",
      "forest-animal-woodland-party-supplies-na_main-1.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "55",
  },
  {
    Name: "MERMAID SHELL PAPER PLATE",
    Price: "8",
    Type: "Plates",
    Description:
      "This Iridescent Sparkle shell paper plates are perfect for your mermaid theme birthday party and bring the ocean to your table. Each pack contains 8 paper plates",
    Theme: "Mermaid",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "23 cm (9 inch)",
    Images: ["mermaid.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "56",
  },
  {
    Name: "BRIDAL SHOWER PAPER PLATES",
    Price: "8",
    Type: "Plates",
    Description:
      "Ready to tie the knot! These Elegant Bridal Shower Paper plates are featuring Greenery Eucalyptus with gold foil rim are stylish addition to your Bridal shower party! Each pack contains 8 paper plates",
    Theme: "Bridal Shower",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 cm (7 inch)",
    Images: ["bridal-shower-dispodable-tableware-gold_description-5.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "57",
  },
  {
    Name: "BEE PAPER PLATES",
    Price: "13",
    Type: "Plates",
    Description:
      "BUZZZZZ....These cute Bee paper plates are featuring yellow honeycomb border with beautiful sunflower and bees pressed on the plate are perfect for bee party! Each pack contains 8 paper plates",
    Theme: "Bee",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 cm (7 inch)",
    Images: ["bee.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "58",
  },
  {
    Name: "WILD ONE PAPER PLATES",
    Price: "9",
    Type: "Plates",
    Description:
      "BE WILD! This pretty paper plate featuring floral ring with cute baby animal’s lion, elephant, giraffe and zebra pressed on the plate. These paper plates are ideal for baby’s first birthday. Each pack contains 8 paper plates",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 cm (7 inch)",
    Images: [
      "new-wild-party-wild-one-golden-wild-part_main-4.jpg",
      "wild-one-birthday-party-decoration-dispo_main-2.jpg",
      "wild-one-birthday-party-decoration-dispo_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "59",
  },
  {
    Name: "OH BABY PAPER PLATES",
    Price: "14",
    Type: "Plates",
    Description:
      "Celebrate your special day with Botanical paper plates featuring “oh baby” text on it. This is perfect for treat everyone in your special day. Each pack contains 8 paper plates",
    Theme: "Baby Shower",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "23 cm (9 inch)",
    Images: ["oh baby.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "60",
  },
  {
    Name: "DINO PAPER PLATES",
    Price: "9",
    Type: "Plates",
    Description:
      "ROAR!!! Creating a fearsome Dinosaur Kingdom party with these beautiful Dino paper plates featuring all kind of colorful dinosaurs will perfect adding to your Dinosaur theme Birthday party. Each pack contains 8 paper plates",
    Theme: "Dino",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 cm (7 inch)",
    Images: [
      "dino (2).jpg",
      "dinosaur-birthday-themed-hot-sale-dispos_main-2.jpg",
      "dinosaur-birthday-themed-hot-sale-dispos_main-4.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "61",
  },

  {
    Name: "BUTTERFLY PAPER PLATES",
    Price: "8",
    Type: "Plates",
    Description:
      "These Large Butterfly Paper Plates are Brighten your day. Featuring colourful flowers in the wings will add more colours to your birthday party. These plates are ideal for fairy, butterfly or garden theme birthday party. Each pack contains 8 paper plates",
    Theme: "Butterfly",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "23 cm (9 inch)",
    Images: [
      "8Pcs 9inch plates_butterfly-theme-party-disposable-tablewa_variants-0.jpg",
      "butterfly-flower-cartoon-party-disposabl_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "63",
  },
  {
    Name: "CIRCUS PAPER PLATES",
    Price: "11",
    Type: "Plates",
    Description:
      "These animal paper plates are perfect for Circus theme party. Featuring red stripes in white paper plates with big cat, lion, monkey, seal, elephant and ringmaster are performing their acts in the circus. Each pack contains 6 paper plates",
    Theme: "Circus",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "23 cm (9 inch)",
    Images: ["circus-themed-party-decorations-striped_main-2.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "64",
  },
  {
    Name: "WHEELS PAPER PLATES",
    Price: "14",
    Type: "Plates",
    Description:
      "VROOM...VROOM...Make your day busy with this beautiful motor vehicles. Featuring first responders, construction and school bus are perfect way to celebrate your Vehicle theme party. Each pack contains 10 paper plates",
    Theme: "Cars",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 cm (7 inch)",
    Images: [
      "plate 7inch10pcs_baby-shower-construction-vehicle-theme-b_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "65",
  },
  {
    Name: "BLOCKS PAPER PLATES",
    Price: "10",
    Type: "Plates",
    Description:
      "This colorful paper plates are fun way to create your Lego or Duplo theme party for your little ones birthday. Featuring colorful Lego blocks prints on the white paper plates will add some excitement to your party table. Each pack contains 8 paper plates",
    Theme: "Building Blocks",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "18 cm (7 inch)",
    Images: [
      "building-blocks.jpg",
      "new-building-blocks-disposable-tableware_main-0.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "66",
  },
  {
    Name: "ICE CREAM PAPER PLATES",
    Price: "15",
    Type: "Plates",
    Description:
      "Are you excited to having summer ice cream party? Add some flavors to your party with this yummy ice pop paper plates. Each pack contains 8 paper plates",
    Theme: "Ice cream",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "9 Inch",
    Images: [
      "9inch Plate 8pcs_summer-ice-cream-disposable-party-tablew_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "67",
  },
  {
    Name: "ICE CREAM PAPER PLATES",
    Price: "13",
    Type: "Plates",
    Description:
      "Are you excited to having summer ice cream party? Add some flavors to your party with this yummy ice pop paper plates. Each pack contains 8 paper plates",
    Theme: "Ice cream",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "9 Inch",
    Images: [
      "23cm Plate 8pcs_summer-theme-activities-ice-cream-series_variants-6.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "68",
  },
  {
    Name: "WHITE & BLUE PAPER STRAWS",
    Price: "5",
    Type: "Straws",
    Description:
      "Decorate your party table with these beautiful White and Blue striped biodegradable paper straw. Perfect for a birthday party, baby shower or family gathering. Each pack contains 10 paper straws.",
    Theme: "Space",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "19.5cm long",
    Images: [
      "Straw 25pcs_outer-space-theme-party-disposable-table_variants-15.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "69",
  },
  {
    Name: "WHITE & YELLOW PAPER STRAWS",
    Price: "9",
    Type: "Straws",
    Description:
      "Paper Straws are the perfect stylish little detail for Birthday party, Baby shower or Special event. Decorate your party table with this simple eco-friendly paper straw. Each pack contains 10 paper straws.",
    Theme: "Space",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "19.5cm long",
    Images: ["bee.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "70",
  },
  {
    Name: "WHITE & PINK PAPER STRAWS",
    Price: "5",
    Type: "Straws",
    Description:
      "Paper Straws are the perfect stylish little detail for Birthday party, Baby shower or Special event. Decorate your party table with this simple eco-friendly paper straw. Each pack contains 10 paper straws.",
    Theme: "Baby Shower",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "19.5cm long",
    Images: ["pink & white.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "71",
  },
  {
    Name: "DINOSAUR STRAW",
    Price: "6",
    Type: "Straws",
    Description:
      "Our Dinosaur Straws are Simple & Beautiful. Decorate your party table with these beautiful straws. Each pack contains 10 paper straws.",
    Theme: "Dino",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "19.5cm long",
    Images: ["dino.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "72",
  },
  {
    Name: "UNICORN PAPER STRAW",
    Price: "6",
    Type: "Straws",
    Description:
      "Add a little magic to your unicorn theme birthday party with these simple beautiful blue straws. Each pack contains 10 paper straws.",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "19.5cm long",
    Images: [
      "UNICORN.jpg",
      "10-pcs-rainbow-unicorn-straw-7-color-styl_main-0.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "73",
  },
  {
    Name: "FLAMINGO PAPER STRAW",
    Price: "5",
    Type: "Straws",
    Description:
      "Enjoy serving refreshing beverages to your guest with these elegant paper straws. These 3D paper straws are great option for Hawaii, flamingo theme party. Each pack contains 10 paper straws.",
    Theme: "Flamingo",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "19.5cm long",
    Images: [
      "10-pcs-flamingo-straw-3-d-straw-bendy-flex_main-0.jpg",
      "10-20-pcs-3-d-flamingo-drinking-straws-jun_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "74",
  },
  {
    Name: "GOLD FOIL PAPER STRAW",
    Price: "4",
    Type: "Straws",
    Description:
      "Decorate your party table with these simple paper straws. These paper straws are environmentally friendly and great choice for any party. Each pack contains 10 paper straws.",
    Theme: "All",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "19.5cm long",
    Images: [
      "gold-foil-paper-straws-biodegradable-di_main-1.jpg",
      "gold-foil-paper-straws-biodegradable-di_main-5.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "75",
  },
  {
    Name: "IN TO THE JUNGLE PAPER CUPS",
    Price: "10",
    Type: "Cup",
    Description:
      "These beautiful pale green paper cups are a perfect addition to your jungle theme birthday party or any kind of events that you wish to celebrate with green. Mix and match with our beautiful paper plates, straws, napkins and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["Jungle.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "76",
  },
  {
    Name: "OUTER SPACE PAPER CUPS",
    Price: "5",
    Type: "Cup",
    Description:
      "These sparkling silver colour cups are perfect for your outer space or astronaut theme birthday party or suitable for any kind of theme party. Mix and match with our beautiful paper plates, straws, napkins and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Space",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "8pcs cups_mermaid-party-colorful-shell-disposable_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "77",
  },
  {
    Name: "MERMAID NAPKINS",
    Type: "Napkin",
    Description:
      "These awesome mermaid napkins are sure to delight at your mermaid theme birthday party. Featuring starfish, sea shells, sea horse and little mermaid will add instant beauty to party settings. Pack contains 10 paper napkins",
    Theme: "Mermaid",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "33 cm X 33 cm ",
    Images: ["little-mermaid-party-decor-mermaid-birth_main-4.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
    ID: "78",
  },
];

export const PartyBox = [
  {
    name: "Ballet",
    title: "Little Ballerina Party Box",
    Inclusions: [
      "6 x Paper Plates (7 inches)",
      "6 x Paper Cups",
      "6 x Paper Hats",
      "6 x Straws",
      "6 x Masks",
      "6 x Blowouts",
    ],
    description:
      "Impress your guests with our beautiful ballet party theme set which is include everything you need to host a beautiful birthday party. This party box is wonderful choice for your little ones birthday.",
  },
  {
    name: "Circus",
    title: "Circus Party Box",
    Inclusions: [
      "6 x Circus Animal Plates ( 9inches)",
      "6 x Circus Animal Paper Cups ",
      "10 x Circus paper Napkins ( 32 cm x 32 cm)",
      "1 x Circus theme Happy Birthday Paper Bunting Garland",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a circus or carnival theme party. Have some fun!!!",
  },
  {
    name: "Wheels",
    title: "Wheels Party Box",
    Inclusions: [
      "10 x Wheels Paper plates  ( 18 cm )",
      "10 x Wheels Paper Cups",
      "20 x Wheels paper Napkins ( 16.5 cm x 16.5 cm)",
      "15 x Wheels Balloons ( 12 inch )",
    ],
    description:
      "Throw a super cute vehicle theme birthday party with our Wheels party box. This party box includes everything you need to host a Vehicle or Construction theme party.",
  },
  {
    name: "Blocks",
    title: "Blocks Party Box",
    Inclusions: [
      "8 x Block party Paper plates (7 inch)",
      "8 x Block party Paper cups",
      "10 x Block party paper Napkins",
      "1 x Blocks party Paper bunting garland ",
    ],
    description:
      "This colorful Blocks party box is fun way to create your Lego or Duplo theme party for your little ones birthday. Featuring a block designs and attractive colors orange, yellow green, red and royal blue. Your kid will love it.  ",
  },
  {
    name: "Ice_cream",
    title: "Ice cream Party Box",
    Inclusions: [
      "16 x Ice Cream Paper Plates  ( 9inches & 23cm)",
      "8 x Ice cream Paper Cups ",
      "20 x Paper Napkins (33x33)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a summer theme party. Have some fun!!!",
  },
  {
    name: "Butterfly",
    title: "Butterfly Party Box",
    Inclusions: [
      "8 x Butterfly Paper Plates ( 9inches)",
      "8 x Butterfly Paper Cups",
      "20 x Butterfly Napkins (33x33)",
      "10 x Pink Paper Straws",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a Butterfly, Fairy and Garden theme party. Have some fun!!!",
  },
  {
    name: "Wild",
    title: "Into The Wild Party Box",
    Inclusions: [
      "10 x Paper Plates",
      "10 x Paper Cups",
      "10 x Paper straws",
      "10 x Napkins (33cm x 33cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a jungle, wild and safari theme party. Have some fun!!!",
  },
  {
    name: "Bee",
    title: "Bee Party Box",
    Inclusions: [
      "8 x Paper Plates",
      "8 x Paper Cups",
      "10 x Paper straws",
      "10 x Napkins (33cm x 33cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a Gender reveal or Bee birthday theme party. Have some fun!!!",
  },
  {
    name: "Space",
    title: "Outer Space Box",
    Inclusions: [
      "8 x Paper Plates",
      "8 x Paper Cups",
      "10 x Paper straws",
      "10 x Napkins (16.5cm x 16.5cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host an outer space theme party. Have some fun!!!",
  },
  {
    name: "Dinosaur",
    title: "Dinosaur Box",
    Inclusions: [
      "10 x Paper Plates",
      "10 x Paper Cups",
      "10 x Paper straws",
      "10 x Napkins (33cm x 33cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a Dinosaur theme party. Have some fun!!!",
  },
  {
    name: "Princess",
    title: "Sweet Princess Box",
    Inclusions: [
      "8 x Paper Plates",
      "8 x Paper Cups",
      "1 x HBD bunting garland",
      "16 x Napkins (25cm x 25cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a Princess theme party. Have some fun!!!",
  },
  {
    name: "Mermaid",
    title: "Mermaid Party Box",
    Inclusions: [
      "8 x Paper Plates",
      "8 x Paper Cups",
      "10 x Paper straws",
      "10 x Napkins (33cm x 33cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a Mermaid theme party. Have some fun!!!",
  },
  {
    name: "Unicorn",
    title: "Unicorn Theme Party Box",
    Inclusions: [
      "8 x Paper Plates",
      "8 x Paper Cups",
      "10 x Paper straws",
      "20 x Napkins (12.5cm x 12.5cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a Unicorn theme party. Have some fun!!!",
  },
  {
    name: "Wild_One",
    title: "Wild One Party Box",
    Inclusions: [
      "8 x Paper Plates",
      "8 x Paper Cups",
      "10 x Paper straws",
      "10 x Napkins (17cm x 17 cm)",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a Wild one theme party. Have some fun!!!",
  },
  {
    name: "Unicorn_2",
    title: "Unicorn Party Box",
    Inclusions: [
      "8 x Paper Plates",
      "8 x Paper Cups",
      "10 x Paper straws",
      "Mini balloon Garland",
    ],
    description:
      "Enjoy your party with this beautiful combination of party box. This party box includes everything that you need to host a unicorn theme party. Have some fun!!!",
  },
];

export const reviews = [
  {
    name: "Sajith Wijewardena",
    description:
      "Excellent customer service, well packed. worth money, highly recomended",
  },
  {
    name: "Nilaksha Praneeth",
    description:
      "Excellent service done in my baby's birthday. Highly recommend",
  },
  {
    name: "hikemp5",
    description: "Love them thanks",
  },
  {
    name: "s.tahe",
    description: "Great trader. Thank you",
  },
  {
    name: "tuaminator14",
    description: "Excellent trade",
  },
  {
    name: "roxanne82",
    description:
      "Wonderful retailer to purchase from. Have not used product yeat as event is not till November. But going by the pics, efficient posting and communication via email, I'm sure balloons will be perfect.",
  },
  {
    name: "ceedubb",
    description:
      "---Item as described: 5/5, Seller communication: 5/5, Delivers on time: 5/5, Item quality: 5/5",
  },
  {
    name: "joshua549",
    description: "Great trader",
  },
  {
    name: "Lovedeep Kaur",
    description:
      "Thank you so much Middlemist. Decoration was fabulous. You did a wonderful job and I love your customer service too good. Highly recommended you never get disappointed 👏👏",
  },
  {
    name: "Devid freg",
    description:
      "Great team with nice smile, and immaculate work. Highly recommend!!",
  },
  {
    name: "Dilshani",
    description:
      "I'm delighted with the event planning and balloon arrangement for my recent celebration. The impeccable attention to detail and beautiful balloon arrangements made my event memorable, receiving numerous compliments. Highly recommend for those seeking an extra special touch. Thank you for making it magical!",
  },
  {
    name: "Kavindra",
    description:
      "I cannot expect more from anywhere else. Had Really good communication with Navinda and they have done all my decos more than I expected.  I highly recommend working with them for the look and feel that you want in order to deliver a terrific event.",
  },
  {
    name: "Reva",
    description:
      "Thank you guys for the amazing setup. We loved it 🥰. I have you as my go to event planner for sure.",
  },
];
