export const MenuItems = [
  { name: "NEW" },
  { name: "PARTY SUPPLIES" },
  { name: "BALLOONS" },
  { name: "SHOP BY THEME" },
  { name: "SHOP BY COLOUR" },
  { name: "SALE" },
];

export const Events = [
  { name: "GENDER REVEAL" },
  { name: "BRIDAL SHOWER" },
  { name: "BABY SHOWER" },
];

export const Items = [
  {
    Name: "MERMAID CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Throw a Beautiful Mermaid theme Birthday party with this elegant mermaid cake topper. Featuring Ocean shells, star fish and little mermaid cake topper will add finishing touch to your beautifully decorated cake. Pack contains 1 Rose gold mermaid cake topper",
    Theme: "Mermaid",
    Material: "Acrylic",
    Colour: "Rose gold",
    Text: "Happy Birthday",
    Dimension: "15 cm x 16 cm",
    Images: [
      "ocean-shell-arylic-happy-birthday-cake-t_main-1.jpg",
      "Y02_1-pc-acrylic-happy-birthday-cake-insert-c_variants-1.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "BIRTHDAY 'QUEEN' CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your Birthday cake at your special day. Add this birthday ‘Queen’ cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Gold Birthday cake topper.",
    Theme: "Queen",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Birthday Queen",
    Dimension: "12 cm",
    Images: ["crown-birthday-king-queen-princess-princ_main-4.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "FLAMINGO CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your Birthday cake at your special day. Add this colourful birthday flamingo cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Flamingo Gold Birthday cake topper.",
    Theme: "Flamingo",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: "7.5 cm x 4.5 cm",
    Images: [
      "1.jpg",
      "1pcs cake topper B_flamingo-pineapple-aloha-letter-cake-top_variants-3 - Copy.jpg",
      "1pcs cake topper B_flamingo-pineapple-aloha-letter-cake-top_variants-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY ANNIVERSARY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Gold Anniversary cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Happy Anniversary cake topper.",
    Theme: "Anniversary",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Anniversary",
    Dimension: undefined,
    Images: ["gold_wedding-cake-topper-acrylic-bride-to-be_variants-17.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "UNICORN CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Featuring cute little girl sitting on the magical unicorn will add extra magic to your unicorn birthday. Add this Elegant Unicorn cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Unicorn cake topper",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "rainbow-unicorn-girl-baby-shower-1st-cak_main-0.jpg",
      "Unicorn girl_unicorn-girl-straw-cake-topper-for-birth_variants-1.jpg",
      "unicorn-girl-straw-cake-topper-for-birth_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "RAINBOW CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Magical Rainbow cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Rainbow cake topper",
    Theme: "Rainbow",
    Material: "Paperboard",
    Colour: undefined,
    Text: undefined,
    Dimension: "14 cm x 10.5 cm",
    Images: [
      "A3_rainbow-unicorn-girl-baby-shower-1st-cak_variants-2.jpg",
      "Rainbow clouds 1_unicorn-girl-straw-cake-topper-for-birth_variants-5.jpg",
      "unicorn-girl-straw-cake-topper-for-birth_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "SAFARI HAPPY BIRTHDAYCAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Cute Animal cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Safari Happy Birthday cake topper",
    Theme: "Jungle",
    Material: "Paperboard",
    Colour: undefined,
    Text: undefined,
    Dimension: "15 cm x 15 cm",
    Images: [
      "black_woodland-animals-cake-decor-soft-clay-li_variants-22 - Copy.jpg",
      "black_woodland-animals-cake-decor-soft-clay-li_variants-22.jpg",
      "jungle-animals-cactus-cake-toppers-happy_main-0 (1).jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "ONE HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this ‘ONE’ cake topper as the finishing touch to your beautifully decorated cake for your little one’s first Birthday party. Pack contains 1 ‘ONE’ Happy Birthday cake topper",
    Theme: "One",
    Material: "Acrylic",
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "garniture-de-gateau-danniversaire-en-ac_main-3.jpg",
      "one-first-birthday-cake-topper-baby-show_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "0-9 NUMBER CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. These Number cake toppers are ideal for birthday cake or cup cakes.",
    Theme: "0-9 Number",
    Material: "Acrylic",
    Colour: "Gold",
    Text: undefined,
    Dimension: "10.8 cm x 4 cm (approx)",
    Images: [
      "5-10-pcs-mirror-surface-cake-topper-acryl_description-10.jpg",
      "5-10-pcs-mirror-surface-cake-topper-acryl_description-16.jpg",
      "set-of-11-pcs-acrylic-numbers-0-9-crown-c_main-0.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Gold Happy Birthday cake topper.",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: ["acrylic-happy-birthday-cake-topper-for-c_main-0.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Gold Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: ["2020-new-laser-cut-cake-party-decoration_main-0.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Silver Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Silver",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: [
      "decoration-de-gateau-dore-et-rose-en-res_main-3.jpg",
      "Silver_ins-birthday-cake-topper-paper-butterfly_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Rose Gold Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Rose Gold",
    Text: "Happy Birthday",
    Dimension: "13 cm x 13.5 cm",
    Images: [
      "2020-happy-birthday-cake-topper-acrylic_main-3.jpg",
      "happy-birthday-cake-topper-silver-glitte_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HE OR SHE CAKETOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 He or She cake topper",
    Theme: "He or She",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "He or She",
    Dimension: "10.5 cm x 15.5 cm",
    Images: [
      "baby-gender-reveal-for-he-or-she-cake-to_main-1.jpg",
      "gender-reveal-acrylic-cake-topper-decora_main-2.jpg",
      "she-or-he-birthday-cake-toppers-boy-or-g_main-4.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "MERMAID CUP",
    Type: "Cup",
    Description:
      "This beautiful iridescent mermaid cups are perfect addition to your mermaid theme birthday party. Each pack contains 8 pieces mermaid paper cup",
    Theme: "Mermaid",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: "7.5 cm x 8.7 cm",
    Images: [
      "8pcs cups_mermaid-party-colorful-shell-disposable_variants-8.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "PRINCESS PAPER CUPS",
    Type: "Cup",
    Description:
      "This beautiful pink paper cup is featuring a magical castle with gold foil pressed elements are perfect addition to your princess birthday party. Each pack contains 8 pieces mermaid paper cup",
    Theme: "Princess",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["princess (2).jpg", "Princess.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "UNICORN PAPER CUPS",
    Type: "Cup",
    Description:
      "This pretty pastel peach unicorn paper cup is beautiful addition to your unicorn theme party. Featuring a fun magical unicorn in the rainbow will add more colours to your birthday party. Each pack contains 8 pieces paper cup",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["0.jpg", "1.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "FLAMINGO PAPER CUPS",
    Type: "Cup",
    Description:
      "ALOHA!!! This Pretty pink flamingo paper cups are perfect addition to your flamingo or Tropical theme party. Featuring gorgeous colours, pair of flamingo, tropical fruit and gold foil details is the perfect way to serve refreshments at your party. Pair them with our flamingo paper plates or pineapple paper plates for fun flamingo or tropical party. Each pack contains 8 pieces paper cup",
    Theme: "Flamingo",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["flamingo-cup.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "BRIDAL SHOWER PAPER CUP",
    Type: "Cup",
    Description:
      "Ready to tie the knot! These Elegant Bridal Shower Paper cups are featuring Greenery Eucalyptus with gold foil rim are perfect addition to your Bridal shower party!. Each pack contains 16 pieces paper cup",
    Theme: "Bridal Shower",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "16pcs Paper Cups_16-pcs-bridal-shower-disposable-tableware_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "BEE PAPER CUP",
    Type: "Cup",
    Description:
      "This beautiful yellow colour paper cups featuring cute bees with yummy honeycomb will add cute addition to your bee theme party. Mix and match with our beautiful paper plates, straws and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Bee",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["bee (2).jpg", "bee.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "SWEET UNICORN PAPER CUPS",
    Type: "Cup",
    Description:
      "This sweet unicorn paper cups are perfect for serve refreshments in your magical unicorn birthday party. This paper cups are sweetest addition to your party and make memorable one. Mix and match with our beautiful paper plates, straws and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "44-pcs-set-pink-cartoon-unicorn-theme-dis_description-5.jpg",
      "unicorn green.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "DINO PAPER CUPS",
    Type: "Cup",
    Description:
      "This cute little Dino paper cups are coolest addition to your dinosaur theme party. Mix and match with our beautiful paper plates, straws, napkins and other decorations. Each pack contains 8 pieces paper cup",
    Theme: "Dino",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["Dino.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "GOLD PAPER CUPS",
    Type: "Cup",
    Description:
      "Celebrate your special moments with these beautiful gold paper cups. You can match with these cups with our “oh baby “paper plates to throw an amazing baby shower party. Mix and match with our beautiful paper plates, straws, napkins and other decorations. Each pack contains 10 pieces paper cup",
    Theme: "Baby Shower",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["IMG_E3019.JPG"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "WILD ONE PAPER CUPS",
    Type: "Cup",
    Description:
      "BE WILD! This pretty paper cups are featuring floral ring with cute baby animals pressed on the paper cups. These paper cups are ideal for baby’s first birthday. Each pack contains 10 paper cups",
    Theme: "Jungle",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["new-wild-party-wild-one-golden-wild-part_main-5.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "BUTTERFLY PAPER CUPS",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this beautiful butterfly paper cup. Featuring floral soft pink, and butterflies in the paper cups are surely impressed your guest. This paper cups are perfect for butterfly, garden or fairy theme party. Each pack contains 8 paper cups",
    Theme: "Butterfly",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "8Pcs cups_butterfly-theme-party-disposable-tablewa_variants-2.jpg",
      "8PCS_pink-butterfly-pattern-plate-cup-straw-s_variants-1.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "CIRCUS PAPER CUPS",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cup will bring joy and fun act for your little one who loved to go to carnival or circus. This paper cups are ideal for Circus or Carnival theme party. Each pack contains 8 paper cups",
    Theme: "Circus",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["circus-theme-party-decorations-striped-a_main-5.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "WHEELS PAPER CUPS",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cup will bring joy and fun for your little one who loves the vehicle. This paper cups are ideal for Wheels or Construction theme party. Each pack contains 10 paper cups",
    Theme: "Cars",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["wheels.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "BLOCKS PAPER CUPS",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cup will bring joy and fun for your little one who loves to play with Blocks or Duplo. This paper cups are ideal for Blocks or Duplo theme party. Each pack contains 8 paper cups",
    Theme: "Building Blocks",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["2.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "PINK PAPER CUPS",
    Type: "Cup",
    Description:
      "Serve the drinks for your guests with this cute party paper cup. This paper cups are perfect for Ice cream theme party. Each pack contains 8 paper cups",
    Theme: "Ice cream",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: ["ice pop.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
];

export const PartyBox = [
  { name: "BOW WOW" },
  { name: "UNDER THE SEA" },
  { name: "BABY IN BLOOM" },
  { name: "BORTANICAL BABY" },
  { name: "JUNGLE ANIMAL" },
  { name: "CONSTRUCTION" },
];

export const reviews = [
  {
    name: "Sarah J.",
    description:
      "Wheeldeal has made buying and selling cars so much easier. The user interface is intuitive and the process is quick and efficient.",
  },
  {
    name: "Michael T.",
    description:
      "I love the safety features Wheeldeal has in place to protect my personal information during transactions. It gives me peace of mind when buying or selling cars.",
  },
  {
    name: "Jessica P.",
    description:
      "I had a great experience using Wheeldeal to sell my old car. It was so simple to list and the process was hassle-free.",
  },
  {
    name: "David H.",
    description:
      "The comparison tools on Wheeldeal are fantastic. I was able to easily compare different cars and make an informed decision on my purchase.",
  },
  {
    name: "Rachel B.",
    description:
      "I highly recommend Wheeldeal to anyone looking to buy or sell a car. It's user-friendly, efficient, and offers a safe and secure trading experience.",
  },
];
