export const MenuItems = [
  { name: "NEW" },
  { name: "PARTY SUPPLIES" },
  { name: "BALLOONS" },
  { name: "SHOP BY THEME" },
  { name: "SHOP BY COLOUR" },
  { name: "SALE" },
];

export const Events = [
  { name: "GENDER REVEAL" },
  { name: "BRIDAL SHOWER" },
  { name: "BABY SHOWER" },
];

export const Items = [
  {
    Name: "MERMAID CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Throw a Beautiful Mermaid theme Birthday party with this elegant mermaid cake topper. Featuring Ocean shells, star fish and little mermaid cake topper will add finishing touch to your beautifully decorated cake. Pack contains 1 Rose gold mermaid cake topper",
    Theme: "Mermaid",
    Material: "Acrylic",
    Colour: "Rose gold",
    Text: "Happy Birthday",
    Dimension: "15 cm x 16 cm",
    Images: [
      "ocean-shell-arylic-happy-birthday-cake-t_main-1.jpg",
      "Y02_1-pc-acrylic-happy-birthday-cake-insert-c_variants-1.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "BIRTHDAY 'QUEEN' CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your Birthday cake at your special day. Add this birthday ‘Queen’ cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Gold Birthday cake topper.",
    Theme: "Queen",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Birthday Queen",
    Dimension: "12 cm",
    Images: ["crown-birthday-king-queen-princess-princ_main-4.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "FLAMINGO CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your Birthday cake at your special day. Add this colourful birthday flamingo cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Flamingo Gold Birthday cake topper.",
    Theme: "Flamingo",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: "7.5 cm x 4.5 cm",
    Images: [
      "1.jpg",
      "1pcs cake topper B_flamingo-pineapple-aloha-letter-cake-top_variants-3 - Copy.jpg",
      "1pcs cake topper B_flamingo-pineapple-aloha-letter-cake-top_variants-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY ANNIVERSARY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Gold Anniversary cake topper to give the finishing touch for your beautifully decorated cake. Pack contains 1 Happy Anniversary cake topper.",
    Theme: "Anniversary",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Anniversary",
    Dimension: undefined,
    Images: ["gold_wedding-cake-topper-acrylic-bride-to-be_variants-17.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "UNICORN CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Featuring cute little girl sitting on the magical unicorn will add extra magic to your unicorn birthday. Add this Elegant Unicorn cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Unicorn cake topper",
    Theme: "Unicorn",
    Material: undefined,
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "rainbow-unicorn-girl-baby-shower-1st-cak_main-0.jpg",
      "Unicorn girl_unicorn-girl-straw-cake-topper-for-birth_variants-1.jpg",
      "unicorn-girl-straw-cake-topper-for-birth_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "RAINBOW CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Magical Rainbow cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Rainbow cake topper",
    Theme: "Rainbow",
    Material: "Paperboard",
    Colour: undefined,
    Text: undefined,
    Dimension: "14 cm x 10.5 cm",
    Images: [
      "A3_rainbow-unicorn-girl-baby-shower-1st-cak_variants-2.jpg",
      "Rainbow clouds 1_unicorn-girl-straw-cake-topper-for-birth_variants-5.jpg",
      "unicorn-girl-straw-cake-topper-for-birth_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "SAFARI HAPPY BIRTHDAYCAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this Cute Animal cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Safari Happy Birthday cake topper",
    Theme: "Jungle",
    Material: "Paperboard",
    Colour: undefined,
    Text: undefined,
    Dimension: "15 cm x 15 cm",
    Images: [
      "black_woodland-animals-cake-decor-soft-clay-li_variants-22 - Copy.jpg",
      "black_woodland-animals-cake-decor-soft-clay-li_variants-22.jpg",
      "jungle-animals-cactus-cake-toppers-happy_main-0 (1).jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "ONE HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this ‘ONE’ cake topper as the finishing touch to your beautifully decorated cake for your little one’s first Birthday party. Pack contains 1 ‘ONE’ Happy Birthday cake topper",
    Theme: "One",
    Material: "Acrylic",
    Colour: undefined,
    Text: undefined,
    Dimension: undefined,
    Images: [
      "garniture-de-gateau-danniversaire-en-ac_main-3.jpg",
      "one-first-birthday-cake-topper-baby-show_main-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "0-9 NUMBER CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. These Number cake toppers are ideal for birthday cake or cup cakes.",
    Theme: "0-9 Number",
    Material: "Acrylic",
    Colour: "Gold",
    Text: undefined,
    Dimension: "10.8 cm x 4 cm (approx)",
    Images: [
      "5-10-pcs-mirror-surface-cake-topper-acryl_description-10.jpg",
      "5-10-pcs-mirror-surface-cake-topper-acryl_description-16.jpg",
      "set-of-11-pcs-acrylic-numbers-0-9-crown-c_main-0.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Gold Happy Birthday cake topper.",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: ["acrylic-happy-birthday-cake-topper-for-c_main-0.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Gold Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: ["2020-new-laser-cut-cake-party-decoration_main-0.jpg"],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Silver Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Silver",
    Text: "Happy Birthday",
    Dimension: undefined,
    Images: [
      "decoration-de-gateau-dore-et-rose-en-res_main-3.jpg",
      "Silver_ins-birthday-cake-topper-paper-butterfly_variants-2.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HAPPY BIRTHDAY CAKE TOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 Rose Gold Happy Birthday cake topper",
    Theme: "Happy Birthday",
    Material: "Acrylic",
    Colour: "Rose Gold",
    Text: "Happy Birthday",
    Dimension: "13 cm x 13.5 cm",
    Images: [
      "2020-happy-birthday-cake-topper-acrylic_main-3.jpg",
      "happy-birthday-cake-topper-silver-glitte_main-3.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
  {
    Name: "HE OR SHE CAKETOPPER",
    Type: "Cake Topper",
    Description:
      "Cake topper is a beautiful way to decorate your cake at your special day. Add this cake topper as the finishing touch to your beautifully decorated cake. Pack contains 1 He or She cake topper",
    Theme: "He or She",
    Material: "Acrylic",
    Colour: "Gold",
    Text: "He or She",
    Dimension: "10.5 cm x 15.5 cm",
    Images: [
      "baby-gender-reveal-for-he-or-she-cake-to_main-1.jpg",
      "gender-reveal-acrylic-cake-topper-decora_main-2.jpg",
      "she-or-he-birthday-cake-toppers-boy-or-g_main-4.jpg",
    ],
    BalloonOrPartyItem: "PartyItem",
    New: false,
    Sale: false,
    PartyBox: true,
    BoxType: [],
    BalloonType: [],
  },
];

export const PartyBox = [
  { name: "BOW WOW" },
  { name: "UNDER THE SEA" },
  { name: "BABY IN BLOOM" },
  { name: "BORTANICAL BABY" },
  { name: "JUNGLE ANIMAL" },
  { name: "CONSTRUCTION" },
];

export const reviews = [
  {
    name: "Sarah J.",
    description:
      "Wheeldeal has made buying and selling cars so much easier. The user interface is intuitive and the process is quick and efficient.",
  },
  {
    name: "Michael T.",
    description:
      "I love the safety features Wheeldeal has in place to protect my personal information during transactions. It gives me peace of mind when buying or selling cars.",
  },
  {
    name: "Jessica P.",
    description:
      "I had a great experience using Wheeldeal to sell my old car. It was so simple to list and the process was hassle-free.",
  },
  {
    name: "David H.",
    description:
      "The comparison tools on Wheeldeal are fantastic. I was able to easily compare different cars and make an informed decision on my purchase.",
  },
  {
    name: "Rachel B.",
    description:
      "I highly recommend Wheeldeal to anyone looking to buy or sell a car. It's user-friendly, efficient, and offers a safe and secure trading experience.",
  },
];
